name: Specs

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "jruby"
        include:
          - os: ubuntu
            ruby: head
            experimental: true
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libsqlite3-dev
        gem install bundler
        bundle install --retry 3
    - name: Test with all appraisals
      run: bundle exec rake
